apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-driven-python
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.helloworld
      source: dev.knative.samples/helloworldsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: my-event-function
